manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: SyarifFakhri
      url-base: https://github.com/SyarifFakhri
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-nice-oled
      remote: SyarifFakhri
      revision: main
  self:
    path: config